const beerList = [
  {
    name: 'Helles',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Kolsch',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Witbier',
    malt: 'Light',
    body: 'Full-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'Wheatbeer',
    malt: 'Light',
    body: 'Full-Bodied',
    balance: 'Yeast Forward',
  },
  { name: 'APA', malt: 'Light', body: 'Light-Bodied', balance: 'Hop Forward' },
  { name: 'IPA', malt: 'Light', body: 'Light-Bodied', balance: 'Hop Forward' },
  {
    name: 'Bitter',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Hop Forward',
  },
  {
    name: 'Berliner Weisse',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'Blonde Ale',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },

  {
    name: 'Eisbock',
    malt: 'Light',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Flanders Red Ale',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'Fruit Beer',
    malt: 'Light',
    body: 'Full-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'Gose',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'Hefeweizen',
    malt: 'Light',
    body: 'Full-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'Irish Red Ale',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Kellerbier',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Lambic',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'Mild Ale',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Rye Beer',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Vienna Lager',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Pilsner',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  { name: 'NEIPA', malt: 'Light', body: 'Full-Bodied', balance: 'Hop Forward' },
  {
    name: 'Saison',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'Sour',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'Steam Beer',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Tripel',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'West Coast IPA',
    malt: 'Light',
    body: 'Light-Bodied',
    balance: 'Hop Forward',
  },
  {
    name: 'Dunkel',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
  { name: 'Stout', malt: 'Dark', body: 'Full-Bodied', balance: 'Malt Forward' },
  {
    name: 'Porter',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Schwarzbier',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
  { name: 'Bock', malt: 'Dark', body: 'Full-Bodied', balance: 'Malt Forward' },
  {
    name: 'DoppelBock',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Dunkelweizen',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Yeast Forward',
  },
  {
    name: 'EisBock',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Imperial Stout',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Dark Mild',
    malt: 'Dark',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Table Beer',
    malt: 'Dark',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Brown Ale',
    malt: 'Dark',
    body: 'Light-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Old Ale',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Barleywine',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
  {
    name: 'Scotch Ale',
    malt: 'Dark',
    body: 'Full-Bodied',
    balance: 'Malt Forward',
  },
];

export default beerList;
